charts/common/Chart.yaml, charts/common/templates/_deployment.yaml
Additional env variable for consortia
=> Rancher 901

charts/mod-authtoken/Chart.yaml
to enable additional env variable.
=> RANCHER-903

charts/common/Chart.yaml, charts/mod-consortia/Chart.yaml, charts/mod-consortia/values.yaml
Implements default system user password for mod-consortia
=> RANCHER-926 SYSTEM_USER_PASSWORD env variable add

charts/common/Chart.yaml, charts/edge-fqm/.helmignore, charts/edge-fqm/Chart.yaml, charts/edge-fqm/templates/NOTES.txt, charts/edge-fqm/templates/app.yaml, charts/edge-fqm/values.yaml, charts/mod-fqm-manager/.helmignore, charts/mod-fqm-manager/Chart.yaml, charts/mod-fqm-manager/templates/NOTES.txt, charts/mod-fqm-manager/templates/app.yaml, charts/mod-fqm-manager/values.yaml, charts/mod-lists/.helmignore, charts/mod-lists/Chart.yaml, charts/mod-lists/templates/NOTES.txt, charts/mod-lists/templates/app.yaml, charts/mod-lists/values.yaml
New modules included. Please review.
=> Rancher-970

charts/mod-inn-reach/Chart.yaml, charts/mod-inn-reach/values.yaml
See: [RANCHER-1007](https://issues.folio.org/browse/RANCHER-1007)
=> Adjust mod-inn-reach helm chart with new INNREACH_TENANTS env variable

charts/common/Chart.yaml, charts/mod-consortia/Chart.yaml, charts/mod-consortia/values.yaml
a proper config PR, removing duplicated value and use db-connect-parameters secret.
=> Rancher-1046

charts/common/Chart.yaml, charts/edge-courses/.helmignore, charts/edge-courses/Chart.yaml, charts/edge-courses/templates/NOTES.txt, charts/edge-courses/templates/app.yaml, charts/edge-courses/values.yaml, charts/mod-agreements/Chart.yaml, charts/mod-agreements/values.yaml, charts/mod-service-interaction/Chart.yaml, charts/mod-service-interaction/values.yaml
=> RANCHER-864 mod-agreements & service-interaction RAM requests increase according to value of 75%.

charts/mod-entities-links/Chart.yaml, charts/mod-entities-links/values.yaml, charts/mod-inn-reach/Chart.yaml, charts/mod-inn-reach/values.yaml, charts/mod-pubsub/Chart.yaml, charts/mod-pubsub/values.yaml
Jira: https://issues.folio.org/browse/RANCHER-1077
=> RANCHER-1077 Check and add missing SYSTEM_USER_PASSWORD for modules

charts/mod-inn-reach/Chart.yaml, charts/mod-inn-reach/values.yaml
https://issues.folio.org/browse/RANCHER-1089
=> RANCHER-1089 Add SYSTEM_USER_NAME for mod-inn-reach

charts/mod-marc-migrations/.helmignore, charts/mod-marc-migrations/Chart.yaml, charts/mod-marc-migrations/templates/NOTES.txt, charts/mod-marc-migrations/templates/app.yaml, charts/mod-marc-migrations/values.yaml
Adding new module [mod-marc-migrations](https://github.com/folio-org/mod-marc-migrations)
=> RANCHER-1122 add new module

charts/mod-batch-print/.helmignore, charts/mod-batch-print/Chart.yaml, charts/mod-batch-print/templates/NOTES.txt, charts/mod-batch-print/templates/app.yaml, charts/mod-batch-print/values.yaml
Jira: https://issues.folio.org/browse/RANCHER-1139
=> RANCHER-1139 Add module mod-batch-print to rancher

charts/mod-circulation/values.yaml
RANCHER-1147 adjust mod-circulation helm chart by adding below env vфrs into chart
=> RANCHER-1147 adjust mod-circulation helm chart

charts/mod-requests-mediated/.helmignore, charts/mod-requests-mediated/Chart.yaml, charts/mod-requests-mediated/templates/NOTES.txt, charts/mod-requests-mediated/templates/app.yaml, charts/mod-requests-mediated/values.yaml, charts/mod-tlr/.helmignore, charts/mod-tlr/Chart.yaml, charts/mod-tlr/templates/NOTES.txt, charts/mod-tlr/templates/app.yaml, charts/mod-tlr/values.yaml
Jira:
https://issues.folio.org/browse/RANCHER-1163
https://issues.folio.org/browse/RANCHER-1164
=> RANCHER-1163, RANCHER-1164 Add new module mod-tlr and mod-requests-mediated

LICENSE.txt, README.md
https://folio-org.atlassian.net/browse/RANCHER-1183
=> RANCHER-1183 Write a README (documentation) for folio-helm charts usage

.editorconfig, charts/folio-common/Chart.yaml, charts/folio-common/templates/_deployment.tpl, charts/folio-common/templates/_hpa.tpl, charts/folio-common/templates/_service.tpl, charts/okapi/Chart.yaml, charts/okapi/resources/hazelcast-config.xml, charts/okapi/templates/_configmap.tpl, charts/okapi/templates/application.yaml, charts/okapi/templates/hazelcast-rbac.yaml, charts/okapi/templates/service.yaml, charts/okapi/values.yaml
Jira: https://folio-org.atlassian.net/browse/RANCHER-1228
Update _hpa.tpl
Update values.yaml
Update service.yaml
=> RANCHER-1228 Implement okapi clustering in Karate tests

charts/mod-tlr/Chart.yaml, charts/mod-tlr/values.yaml
Jira: https://folio-org.atlassian.net/browse/RANCHER-1642
=> RANCHER-1642 Add kafka and okapi intgration for mod-tlr

charts/mod-consortia-keycloak/Chart.yaml, charts/mod-consortia-keycloak/values.yaml, charts/mod-login-keycloak/Chart.yaml, charts/mod-login-keycloak/values.yaml, charts/mod-roles-keycloak/Chart.yaml, charts/mod-roles-keycloak/values.yaml, charts/mod-scheduler/Chart.yaml, charts/mod-scheduler/values.yaml, charts/mod-users-keycloak/Chart.yaml, charts/mod-users-keycloak/values.yaml
Ralted Jira Ticket:
[RANCHER-1652: Eureka. Add OKAPI_URL env variable to the *-keycloak modules.](https://folio-org.atlassian.net/browse/RANCHER-1652)
=> RANCHER-1652: Eureka: Add OKAPI_URL env variable to the *-keycloak modules.

README.md, charts/folio-common/Chart.yaml, charts/folio-common/templates/_configmap.tpl, charts/folio-common/templates/_deployment.tpl, charts/folio-common/templates/_helpers.tpl, charts/folio-common/templates/_serviceaccount.tpl, charts/mod-agreements/Chart.yaml, charts/mod-agreements/custom.yaml, charts/mod-agreements/resources/jmx-install.sh, charts/mod-agreements/resources/prometheus-jmx-config.yaml, charts/mod-agreements/templates/application.yaml, charts/mod-agreements/values.yaml, example/resources/jmx-install.sh, example/resources/prometheus-jmx-config.yaml, example/values.yaml
Jira: https://folio-org.atlassian.net/browse/RANCHER-1726
=> RANCHER-1726 Implement JMX integration for Helm charts

charts/mod-okapi-facade/.helmignore, charts/mod-okapi-facade/Chart.yaml, charts/mod-okapi-facade/templates/NOTES.txt, charts/mod-okapi-facade/templates/application.yaml, charts/mod-okapi-facade/values.yaml
Related Jira Ticket:
[RANCHER-1745: Include new module mod-okapi-facade into Eureka configs(testing), scripts(folioHelm), helm charts(folio-helm repo) and so on](https://folio-org.atlassian.net/browse/RANCHER-1745)
Related Pull Request:
https://github.com/folio-org/pipelines-shared-library/pull/641
=> RANCHER-1745: add Helm Chart for mod-okapi-facade

charts/mod-circulation-bff/Chart.yaml, charts/mod-circulation-bff/values.yaml
Add System User integration to mod-circulation-bff module.
Related Jira ticket:
[RANCHER-1900: Failed to deploy mod-circulation-bff-1.1.0-SNAPSHOT.21 module to folio-testing-sprint environment]( https://folio-org.atlassian.net/browse/RANCHER-1900)
=> RANCHER-1900: add systemuser integration

charts/mod-invoice-storage/Chart.yaml, charts/mod-invoice-storage/values.yaml, charts/mod-organizations-storage/Chart.yaml, charts/mod-organizations-storage/values.yaml
Related Jira ticket:
[RANCHER-1907:] Add kafka support for mod-invoice-storage, mod-organizations-storage(https://folio-org.atlassian.net/browse/RANCHER-1907)
=> RANCHER-1907: add integration with Kafka

charts/mod-login-saml/Chart.yaml, charts/mod-login-saml/values.yaml
Jira: https://folio-org.atlassian.net/browse/RANCHER-1920
=> RANCHER-1920 mod-login-saml fails on CI CG pipelines

charts/mod-camunda/Chart.yaml, charts/mod-camunda/values.yaml, charts/mod-workflow/Chart.yaml, charts/mod-workflow/values.yaml
Related Jira ticket:
[RANCHER-1875: Help setting up mod-camunda and mod-workflow to interact with Kafka in Aggies Rancher](https://folio-org.atlassian.net/browse/RANCHER-1875)
=> RANCHER-1875: add integration with Kafka for 'mod-camunda and 'mod-workflow'

charts/mod-linked-data-import/.helmignore, charts/mod-linked-data-import/Chart.yaml, charts/mod-linked-data-import/templates/NOTES.txt, charts/mod-linked-data-import/templates/application.yaml, charts/mod-linked-data-import/values.yaml
Jira: https://folio-org.atlassian.net/browse/RANCHER-2563
=> RANCHER-2563 Add new deployment config for mod-linked-data-import
